Ext.define('snap.model.MyAccountHolder', {
    extend: 'snap.model.Base',
    fields: [
        {type: 'int', name: 'id'},
        {type: 'int', name: 'partnerid'},

        {type: 'string', name: 'partnercusid'},
        {type: 'string', name: 'email'},
        {type: 'string', name: 'phoneno'},
        {type: 'string', name: 'password'},
        {type: 'string', name: 'oldpassword'},
        {type: 'string', name: 'preferredlang'},
        {type: 'string', name: 'fullname'},
        {type: 'string', name: 'campaigncode'},
        {type: 'string', name: 'accountholdercode'},
        {type: 'string', name: 'xaubalance'},
        {type: 'string', name: 'amountbalance'},
        {type: 'string', name: 'mykadno'},
        //{type: 'string', name: 'occupation'},
        {type: 'int', name: 'occupationcategoryid'},
        {type: 'int', name: 'occupationsubcategoryid'},
        {type: 'string', name: 'referralbranchcode'},
        {type: 'string', name: 'referralbranchname'},
        {type: 'string', name: 'referralsalespersoncode'},
        {type: 'string', name: 'referralintroducercode'},
        {type: 'string', name: 'pincode'},
        {type: 'string', name: 'sapacebuycode'},
        {type: 'string', name: 'sapacesellcode'},
        {type: 'int', name: 'bankid'},
        {type: 'string', name: 'accountname'},
        {type: 'string', name: 'accountnumber'},
        {type: 'string', name: 'accounttype'},
        
        {type: 'string', name: 'nokfullname'},
        {type: 'string', name: 'nokmykadno'},
        {type: 'string', name: 'nokbankid'},
        {type: 'string', name: 'nokaccountnumber'},
        {type: 'int', name: 'investmentmade'},
        {type: 'int', name: 'ispep'},
        {type: 'string', name: 'pepdeclaration'},
        {type: 'boolean', name: 'kycpastday'},
        {type: 'int', name: 'kycstatus'},
        {type: 'int', name: 'amlastatus'},
        {type: 'string', name: 'statusremarks'},
        {type: 'date', name: 'emailtriggeredon'},
        {type: 'date', name: 'emailverifiedon'},
        {type: 'int', name: 'status'},
        {type: 'boolean', name: 'dormant'},
        {type: 'date', name: 'passwordmodified'},
        {type: 'date', name: 'lastloginon'},
        {type: 'string', name: 'lastloginip'},
        {type: 'date', name: 'verifiedon' },
        {type: 'string', name: 'addressline1' },
        {type: 'string', name: 'addressline2' },
        {type: 'string', name: 'addresscity' },
        {type: 'string', name: 'addresspostcode' },
        {type: 'string', name: 'addressstate' },
        {type: 'date', name: 'createdon'},
        {type: 'int', name: 'createdby'},
        {type: 'date', name: 'modifiedon'},
        {type: 'int', name: 'modifiedby'},
        {type: 'string', name: 'createdbyname'},
        {type: 'float', name: 'loantotal'},
        {type: 'float', name: 'loanbalance'},
        {type: 'date', name: 'loanapprovedate'},
        {type: 'string', name: 'loanapproveby'},
        {type: 'int', name: 'loanstatus'},
        {type: 'string', name: 'loanreference'},
        {type: 'int', name: 'iskycmanualapproved'},
    ]
});
