Ext.define('snap.model.MyGoldTransaction', {
    extend: 'snap.model.Base',
    fields: [
        {type: 'int', name: 'id'},
        {type: 'float', name: 'originalamount'},
        {type: 'string', name: 'settlementmethod'},
        {type: 'string', name: 'salespersoncode'},
        {type: 'string', name: 'refno'},
        {type: 'int', name: 'orderid'},
        {type: 'int', name: 'status'},
        {type: 'date', name: 'transactiondate'},
        {type: 'date', name: 'completedon'},
        {type: 'date', name: 'failedon'},
        {type: 'date', name: 'disbursedon'},
        {type: 'date', name: 'createdon'},
        {type: 'int', name: 'createdby'},
        {type: 'date', name: 'modifiedon'},
        {type: 'int', name: 'modifiedby'},

        {type: 'int', name: 'ordpartnerid'},
        {type: 'int', name: 'ordbuyerid'},
        {type: 'string', name: 'ordorderno'},
        {type: 'string', name: 'ordtype'},
        {type: 'float', name: 'ordprice'},
        {type: 'float', name: 'ordfpprice'},
        {type: 'float', name: 'ordxau'},
        {type: 'float', name: 'ordamount'},
        {type: 'float', name: 'ordfee'},
        {type: 'float', name: 'orddiscountprice'},
        {type: 'float', name: 'orddiscountinfo'},
        {type: 'float', name: 'ordfeetypename'},
        {type: 'string', name: 'ordremarks'},
        {type: 'float', name: 'ordbookingprice'},
        {type: 'date', name: 'ordbookingon'},
        {type: 'date', name: 'ordconfirmon'},
        {type: 'date', name: 'ordcancelon'},
        {type: 'int', name: 'ordstatus'},

        {type: 'float', name: 'pdtamount'},
        {type: 'string', name: 'pdtpaymentrefno'},
        {type: 'string', name: 'pdtgatewayrefno'},
        {type: 'string', name: 'pdtsourcerefno'},
        {type: 'string', name: 'pdtsigneddata'},
        {type: 'string', name: 'pdtlocation'},
        {type: 'float', name: 'pdtgatewayfee'},
        {type: 'float', name: 'pdtcustomerfee'},
        {type: 'string', name: 'pdttoken'},
        {type: 'int', name: 'pdtstatus'},
        {type: 'date', name: 'pdttransactiondate'},
        {type: 'date', name: 'pdtrequestedon'},
        {type: 'date', name: 'pdtsuccesson'},
        {type: 'date', name: 'pdtfailedon'},
        {type: 'date', name: 'pdtrefundedon'},

        {type: 'string', name: 'createdbyname'},
        {type: 'string', name: 'modifiedbyname'},
    ]
});
            
       