Ext.define('snap.model.Order', {
    extend: 'snap.model.Base',
    fields: [
        	{type: 'int', name: 'id'},
			{type: 'int', name: 'partnerid'},
			{type: 'int', name: 'buyerid'},
			{type: 'string', name: 'partnerrefid'},
			{type: 'string', name: 'orderno'},
			{type: 'int', name: 'pricestreamid'},
			{type: 'int', name: 'salespersonid'},
			{type: 'string', name: 'apiversion'},
            {type: 'string', name: 'type'},
			{type: 'int', name: 'productid'},
			{type: 'boolean', name: 'isspot'},
			{type: 'float', name: 'price'},
			{type: 'int', name: 'byweight'},
            {type: 'float', name: 'xau'},
            {type: 'float', name: 'amount'},
            {type: 'float', name: 'fee'},
            {type: 'string', name: 'remarks'},
            {type: 'date', name: 'bookingon'},
            {type: 'float', name: 'bookingprice'},
            {type: 'int', name: 'bookingpricestreamid'},
            {type: 'date', name: 'confirmon'},
            {type: 'int', name: 'confirmby'},
            {type: 'float', name: 'confirmpricestreamid'},
            {type: 'float', name: 'confirmprice'},
            {type: 'boolean', name: 'reconciled'},
            {type: 'date', name: 'reconciledon'},
            {type: 'int', name: 'reconciledby'},
            {type: 'string', name: 'reconciledsaprefno'},
			{type: 'date', name: 'createdon'},
			{type: 'int', name: 'createdby'},
			{type: 'date', name: 'modifiedon'},
			{type: 'int', name: 'modifiedby'},
			{type: 'int', name: 'status'},


            {type: 'string', name: 'uuid'},
            {type: 'float', name: 'fpprice'},
            {type: 'string', name: 'feetypename'},
            {type: 'string', name: 'buyername'},
            {type: 'string', name: 'salespersonname'},
            {type: 'string', name: 'productname'},
            {type: 'string', name: 'productcode'},
            {type: 'string', name: 'confirmbyname'},
            {type: 'string', name: 'reconciledbyname'},
            {type: 'string', name: 'cancelbyname'},
			{type: 'string', name: 'partnername'},
            {type: 'string', name: 'partnercode'},
            {type: 'string', name: 'priceprovidercode'},
            {type: 'string', name: 'partnerbuycode1'},
            {type: 'string', name: 'partnersellcode1'},
			{type: 'string', name: 'createdbyname'},
			{type: 'string', name: 'modifiedbyname'},
    ]
});
