Ext.define('snap.model.OrderQueue', {
    extend: 'snap.model.Base',
    fields: [
        	{type: 'int', name: 'id'},
            {type: 'int', name: 'orderid'},
			{type: 'int', name: 'partnerid'},
            {type: 'int', name: 'buyerid'},
			{type: 'string', name: 'partnerrefid'},
			{type: 'string', name: 'orderqueueno'},
			{type: 'int', name: 'salespersonid'},
			{type: 'string', name: 'apiversion'},
            {type: 'string', name: 'ordertype'},
            {type: 'string', name: 'queuetype'},
            {type: 'date', name: 'expireon'},
			{type: 'int', name: 'productid'},
			{type: 'float', name: 'pricetarget'},
			{type: 'int', name: 'byweight'},
            {type: 'float', name: 'xau'},
            {type: 'float', name: 'amount'},
            {type: 'string', name: 'remarks'},
            {type: 'date', name: 'cancelon'},
            {type: 'int', name: 'cancelby'},
            {type: 'int', name: 'matchpriceid'},
            {type: 'date', name: 'matchon'},
            {type: 'string', name: 'notifyurl'},
            {type: 'string', name: 'notifymatchurl'},
            {type: 'string', name: 'successnotifyurl'},
            {type: 'int', name: 'reconciled'},
            {type: 'date', name: 'reconciledon'},
            {type: 'int', name: 'reconciledby'},
			{type: 'date', name: 'createdon'},
			{type: 'int', name: 'createdby'},
			{type: 'date', name: 'modifiedon'},
			{type: 'int', name: 'modifiedby'},
			{type: 'int', name: 'status'},

            {type: 'string', name: 'orderno'},
            {type: 'int', name: 'pricesourceid'},
            {type: 'string', name: 'salespersonname'},
            {type: 'string', name: 'buyername'},
            {type: 'string', name: 'productname'},
            {type: 'string', name: 'cancelbyname'},
            {type: 'string', name: 'reconciledbyname'},
			{type: 'string', name: 'partnername'},
            {type: 'string', name: 'partnercode'},
            {type: 'float', name: 'companybuyppg'},
            {type: 'float', name: 'companysellppg'},
			{type: 'string', name: 'createdbyname'},
			{type: 'string', name: 'modifiedbyname'},
			{type: 'string', name: 'effectiveon'},
    ]
});
