Ext.define('snap.model.Partner', {
    extend: 'snap.model.Base',
    fields: [
        { type: 'int', name: 'id' },
        { type: 'string', name: 'code' },
        { type: 'string', name: 'name' },
		{ type: 'string', name: 'address' },
        { type: 'string', name: 'postcode'},
        { type: 'string', name: 'state' },
        { type: 'string', name: 'type' },
        { type: 'string', name: 'corepartner' },
        { type: 'string', name: 'branchname'},
        { type: 'int', name: 'pricesourceid' },
        { type: 'int', name: 'salespersonid' },
        { type: 'int', name: 'tradingscheduleid'},
        { type: 'string', name: 'sapcompanysellcode1' },
        { type: 'string', name: 'sapcompanybuycode1' },
        { type: 'string', name: 'sapcompanysellcode2' },
        { type: 'string', name: 'sapcompanybuycode2' },
        { type: 'string', name: 'dailybuylimitxau' },
        { type: 'string', name: 'dailyselllimitxau' },
        { type: 'int', name: 'pricelapsetimeallowance' },
        { type: 'string', name: 'orderingmode' },
        { type: 'int', name: 'autosubmitorder' },
        { type: 'string', name: 'sharedgv' },
        { type: 'int', name: 'autocreatematchedorder' },
        { type: 'int', name: 'orderconfirmallowance' },
        { type: 'int', name: 'ordercancelallowance' },
        { type: 'string', name: 'calculatormode' },
        { type: 'string', name: 'createdon' },
        { type: 'string', name: 'createdby' },
        { type: 'string', name: 'modifiedon' },
        { type: 'string', name: 'modifiedby' },        
        { type: 'int', name: 'status' },	
        { type: 'string', name: 'group' },	
        { type: 'int', name: 'parent' },		
    ]
});
