Ext.define('snap.model.PartnerService', {
    extend: 'snap.model.Base',
    fields: [
        {type: 'int', name: 'id'},
        {type: 'int', name: 'partnerid'},
        {type: 'int', name: 'partnersapgroup'},
        {type: 'int', name: 'productid'},
        {type: 'int', name: 'pricesourcetypeid'},
        {type: 'float', name: 'refineryfee'},
        {type: 'float', name: 'premiumfee'},
        {type: 'float', name: 'redemptionpremiumfee'},
        {type: 'float', name: 'redemptioncommission'},
        {type: 'float', name: 'redemptioninsurancefee'},
        {type: 'float', name: 'redemptionhandlingfee'},
        {type: 'int', name: 'includefeeinprice'},
        {type: 'int', name: 'canbuy'},
        {type: 'int', name: 'cansell'},
        {type: 'int', name: 'canqueue'},
        {type: 'int', name: 'canredeem'},
        {type: 'float', name: 'clickminxau'},
        {type: 'float', name: 'clickmaxau'},

        {type: 'float', name: 'buyclickminxau'},
        {type: 'float', name: 'buyclickmaxau'},
        {type: 'float', name: 'sellclickminxau'},
        {type: 'float', name: 'sellclickmaxau'},
        {type: 'float', name: 'dailybuylimitxau'},
        {type: 'float', name: 'dailyselllimitxau'},

        {type: 'string', name: 'specialpricetype'},
        {type: 'float', name: 'specialpricecondition'},
        {type: 'float', name: 'specialpricecompanybuyoffset'},
        {type: 'float', name: 'specialpricecompanyselloffset'},
        {type: 'date', name: 'createdon'},
        {type: 'int', name: 'createdby'},
        {type: 'date', name: 'modifiedon'},
        {type: 'int', name: 'modifiedby'},
        {type: 'int', name: 'status'},
        {type: 'string', name: 'partnername'},
        {type: 'string', name: 'partnercode'},
        {type: 'string', name: 'productname'},
        {type: 'string', name: 'productcode'},
        {type: 'string', name: 'createdbyname'},
        {type: 'string', name: 'modifiedbyname'},
    ]
});
