Ext.define('snap.model.Replenishment', {
    extend: 'snap.model.Base',
    fields: [
        { type: 'string', name: 'branchname', text: 'Partner ID' },
        { type: 'string', name: 'branchcode', text: 'Partner ID' },
        { type: 'string', name: 'productname', text: 'Partner ID' },
        { type: 'string', name: 'salesname', text: 'Partner ID' },
        { type: 'string', name: 'branchsapcode', text: 'Partner ID' },
        { type: 'string', name: 'partnercode', text: 'Partner ID' },
        { type: 'int', name: 'id', text: 'ID' },
        { type: 'int', name: 'partnerid', text: 'Partner ID' },
        { type: 'int', name: 'branchid', text: 'Partner ID' },
        { type: 'int', name: 'salespersonid', text: 'Sales Person ID' },
        { type: 'string', name: 'replenishmentno', text: 'Replenishment No.' },
        { type: 'string', name: 'sapwhscode', text: 'SAP Whs Code' },
        { type: 'string', name: 'saprefno', text: 'SAP Ref No.' },
        { type: 'string', name: 'type', text: 'Type' },
        { type: 'int', name: 'productid', text: 'Product ID' },
        { type: 'string', name: 'serialno', text: 'Serial No.' },
        { type: 'int', name: 'status', text: 'Status' },
        { type: 'string', name: 'sapresponsestatus', text: 'SAP Response Status' },
        { type: 'string', name: 'sapresponseon', text: 'SAP Response On' },
        { type: 'string', name: 'schedule', text: 'Schedule' },
        { type: 'date', name: 'replenishedon', text: 'Replenished On' },
        { type: 'date', name: 'createdon', text: 'Created On' },
        { type: 'int', name: 'createdby', text: 'Created By' },
        { type: 'string', name: 'createdbyname', text: 'Created By' },
        { type: 'date', name: 'modifiedon', text: 'Modified On' },
        { type: 'int', name: 'modifiedby', text: 'Modified By' },
        { type: 'string', name: 'modifiedbyname', text: 'Modified By' },
    ]
});