Ext.define('snap.model.AnpPool', {
	extend: 'snap.model.Base',
	alias: 'viewmodel.anppool-anppool',
    fields: [
		{type: 'int', name: 'id'},
		{type: 'int', name: 'partnerid'},
		{type: 'string', name: 'operationtype'},
		{type: 'int', name: 'orderid'},
		{type: 'float', name: 'beginprice'},
		{type: 'int', name: 'beginpriceid'},
		{type: 'float', name: 'endprice'},
		{type: 'int', name: 'endpriceid'},
		{type: 'float', name: 'amountppg'},
		{type: 'float', name: 'amount'},
		{type: 'string', name: 'partnername'},
		{type: 'string', name: 'orderno'},
		{type: 'string', name: 'ordertype'},
		{type: 'string', name: 'orderxau'},
		{type: 'string', name: 'ordercreatedon'},
		{type: 'string', name: 'p1buyprice'},
		{type: 'string', name: 'p1sellprice'},
		{type: 'string', name: 'p1priceon'},
		{type: 'string', name: 'p2buyprice'},
		{type: 'string', name: 'p2sellprice'},
		{type: 'string', name: 'p2priceon'},
		{type: 'string', name: 'p3buyprice'},
		{type: 'string', name: 'p3sellprice'},
		{type: 'string', name: 'p3priceon'},
		{type: 'string', name: 'p1pricestreamid'},
		{type: 'string', name: 'p2pricestreamid'},
		{type: 'string', name: 'p3pricestreamid'},
		{type: 'string', name: 'status'},
	],
});