Ext.define('snap.model.Logistic', {
    extend: 'snap.model.Base',
    fields: [
        {type: 'int', name: 'id'},
        {type: 'string', name: 'type'},
        {type: 'int', name: 'typeid'},
        {type: 'int', name: 'partnerid'},
        {type: 'int', name: 'vendorid'},
        {type: 'int', name: 'senderid'},
        {type: 'string', name: 'awbno'},
        {type: 'string', name: 'contactname1'},
        {type: 'string', name: 'contactname2'},
        {type: 'string', name: 'contactno1'},
        {type: 'string', name: 'contactno2'},
        {type: 'string', name: 'address1'},
        {type: 'string', name: 'address2'},
        {type: 'string', name: 'address3'},
        {type: 'string', name: 'city'},
        {type: 'string', name: 'postcode'},
        {type: 'string', name: 'state'},
        {type: 'string', name: 'country'},
        {type: 'int', name: 'frombranchid'},
        {type: 'int', name: 'tobranchid'},
        {type: 'date', name: 'senton'},
        {type: 'int', name: 'sentby'},
        {type: 'string', name: 'receivedperson'},
        {type: 'date', name: 'deliveredon'},
        {type: 'int', name: 'deliveredby'},
        {type: 'date', name: 'deliverydate'},
        {type: 'int', name: 'attemps'},
        {type: 'string', name: 'status'},
        {type: 'date', name: 'createdon'},
        {type: 'int', name: 'createdby'},
        {type: 'date', name: 'modifiedon'},
        {type: 'int', name: 'modifiedby'},

        
        {type: 'string', name: 'vendorname'},
        {type: 'string', name: 'sendername'},
        //{type: 'string', name: 'frombranchname'},
        //{type: 'string', name: 'tobranchname'},
        {type: 'string', name: 'sentbyname'},
        {type: 'string', name: 'deliveredbyname'},
        {type: 'string', name: 'createdbyname'},
        {type: 'string', name: 'modifiedbyname'},


    ]
});
