Ext.define('snap.model.MyOrder', {
    extend: 'snap.model.Order',
    
    fields: [
        {type: 'int', name: 'id'},
        {type: 'float', name: 'originalamount'},
        {type: 'string', name: 'settlementmethod'},
        {type: 'string', name: 'salespersoncode'},
        {type: 'string', name: 'campaigncode'},
        {type: 'string', name: 'refno'},
        {type: 'int', name: 'orderid'},
        {type: 'int', name: 'status'},
        {type: 'date', name: 'transactiondate'},
        {type: 'date', name: 'completedon'},
        {type: 'date', name: 'failedon'},
        {type: 'date', name: 'disbursedon'},
        {type: 'date', name: 'createdon'},
        {type: 'int', name: 'createdby'},
        {type: 'date', name: 'modifiedon'},
        {type: 'int', name: 'modifiedby'},

        {type: 'string', name: 'dbmpdtgatewayrefno'},
        {type: 'string', name: 'dbmpdtreferenceno'},
        {type: 'date', name: 'dbmpdtrequestedon'},
        {type: 'string', name: 'dbmpdtaccountholdername'},
        {type: 'string', name: 'dbmpdtaccountholdercode'},
        {type: 'float', name: 'dbmpdtverifiedamount'},
        
        {type: 'string', name: 'achfullname'},
        {type: 'string', name: 'achcode'},
        {type: 'string', name: 'achphoneno'},
        {type: 'string', name: 'achemail'},
        {type: 'string', name: 'achmykadno'},
        {type: 'string', name: 'achpartnercusid'},

        {type: 'int', name: 'ordpartnerid'},
        {type: 'string', name: 'ordproductname'},
        {type: 'int', name: 'ordbuyerid'},
        {type: 'string', name: 'ordorderno'},
        {type: 'string', name: 'ordtype'},
        {type: 'float', name: 'ordprice'},
        {type: 'float', name: 'ordxau'},
        {type: 'float', name: 'ordamount'},
        {type: 'float', name: 'ordfee'},
        {type: 'string', name: 'ordremarks'},
        {type: 'int', name: 'ordisspot'},
        {type: 'date', name: 'ordbookingon'},
        {type: 'date', name: 'ordconfirmon'},
        {type: 'date', name: 'ordcancelon'},
        {type: 'int', name: 'ordstatus'},
        {type: 'string', name: 'ordpartnername'},
        {type: 'float', name: 'originalprice'},

        {type: 'float', name: 'pdtamount'},
        //{type: 'string', name: 'pdtpaymentrefno'},
        //{type: 'string', name: 'pdtgatewayrefno'},
        {type: 'string', name: 'pdtsourcerefno'},
        {type: 'string', name: 'pdtsigneddata'},
        {type: 'string', name: 'pdtlocation'},
        {type: 'float', name: 'pdtgatewayfee'},
        {type: 'float', name: 'pdtcustomerfee'},
        {type: 'string', name: 'pdttoken'},
        {type: 'int', name: 'pdtstatus'},
        {type: 'date', name: 'pdttransactiondate'},
        //{type: 'date', name: 'pdtrequestedon'},
        {type: 'date', name: 'pdtsuccesson'},
        {type: 'date', name: 'pdtfailedon'},
        {type: 'date', name: 'pdtrefundedon'},

        {type: 'float', name: 'dbmamount'},
        {type: 'int', name: 'dbmbankid'},
        {type: 'string', name: 'dbmaccountname'},
        {type: 'string', name: 'dbmaccountnumber'},
        {type: 'int', name: 'dbmacebankcode'},
        {type: 'float', name: 'dbmfee'},
        //{type: 'string', name: 'dbmrefno'},
        {type: 'int', name: 'dbmaccountholderid'},
        {type: 'int', name: 'dbmstatus'},
        //{type: 'string', name: 'dbmgatewayrefno'},
        {type: 'string', name: 'dbmtransactionrefno'},
        //{type: 'date', name: 'dbmrequestedon'},
        {type: 'date', name: 'dbmdisbursedon'},
        {type: 'string', name: 'dbmbankname'},

        {type: 'string', name: 'createdbyname'},
        {type: 'string', name: 'modifiedbyname'},
        {type: 'float', name: 'pricedifference'},
    ]
});
