Ext.define('snap.model.VaultItem', {
    extend: 'snap.model.Base',
    fields: [
        	{type: 'int', name: 'id'},
            {type: 'int', name: 'partnerid'},
			{type: 'int', name: 'vaultlocationid'},
			{type: 'int', name: 'productid'},
			{type: 'float', name: 'weight'},
            {type: 'string', name: 'brand'},
            {type: 'string', name: 'serialno'},
            {type: 'int', name: 'allocated'}, 
            {type: 'date', name: 'allocatedon'}, 
            {type: 'int', name: 'movetovaultlocationid'}, 
            {type: 'date', name: 'moverequestedon'}, 
            {type: 'date', name: 'movecompletedon'}, 
            {type: 'date', name: 'returnedon'}, 
            {type: 'int', name: 'newvaultlocationid'},
            {type: 'string', name: 'deliveryordernumber'},
			{type: 'date', name: 'createdon'},
			{type: 'int', name: 'createdby'},
			{type: 'date', name: 'modifiedon'},
			{type: 'int', name: 'modifiedby'},
            {type: 'int', name: 'status'},

            {type: 'string', name: 'vaultlocationtype'},
            {type: 'string', name: 'vaultlocationdefault'},
            {type: 'string', name: 'vaultlocationname'},
            {type: 'int', name: 'movetolocationpartnerid'},
            {type: 'string', name: 'movetovaultlocationname'},
            {type: 'string', name: 'newvaultlocationname'},
            
            {type: 'string', name: 'partnername'},
            {type: 'string', name: 'partnercode'},
            {type: 'string', name: 'productcode'},
            {type: 'string', name: 'productname'},
            {type: 'string', name: 'createdbyname'},
            {type: 'string', name: 'modifiedbyname'},
    ]
});
