-- Insert into event trigger
INSERT INTO `eventtrigger` (`etr_id`, `etr_grouptypeid`, `etr_moduleid`, `etr_actionid`, `etr_matcherclass`, `etr_processorclass`, `etr_messageid`, `etr_observableclass`, `etr_oldstatus`, `etr_newstatus`, `etr_objectclass`, `etr_storetolog`, `etr_groupidfieldname`, `etr_evalcode`, `etr_createdon`, `etr_modifiedon`, `etr_status`, `etr_createdby`, `etr_modifiedby`) VALUES
(DEFAULT, 0, 3, 11, '\\Snap\\object\\DefaultEventTriggerMatcher', '\\Snap\\object\\EmailEventProcessor', 7, '\\Snap\\manager\\BankVaultManager', 1, 2, '\\Snap\\object\\VaultItem', '1', 'partnerid', '', '2021-03-03 06:45:01', '2021-05-04 03:39:45', 1, 11, 11),
(DEFAULT, 0, 3, 11, '\\Snap\\object\\DefaultEventTriggerMatcher', '\\Snap\\object\\EmailEventProcessor', 10, '\\Snap\\manager\\BankVaultManager', 2, 3, '\\Snap\\object\\VaultItem', '1', 'partnerid', '', '2021-05-03 09:36:26', '2021-05-04 03:40:09', 1, 11, 11);

-- Insert into event message

INSERT INTO `eventmessage` (`evm_id`, `evm_code`, `evm_replace`, `evm_subject`, `evm_content`, `evm_createdon`, `evm_modifiedon`, `evm_createdby`, `evm_modifiedby`, `evm_status`) VALUES
(DEFAULT, 'Gold Transfer for BMMB Vault', '##SERIALNO##||##OTHERPARAM_serialno##,##VAULTFROM##||##OTHERPARAM_vaultfrom##,##VAULTTO##||##OTHERPARAM_vaultto##,## to ##||', 'Kilobar transfer from ##VAULTFROM## to ##VAULTTO##', '<div style=\"\"><div style=\"color: rgb(0, 0, 0);\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\">Dear Sir/ Madam,</font></div><div style=\"color: rgb(0, 0, 0);\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><br></font></div><div style=\"color: rgb(0, 0, 0);\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\">Please be informed that kilobar serial no&nbsp;<b>##SERIALNO##</b></font>&nbsp;from <b>##VAULTFROM## </b>was transferred to<b> ##VAULTTO##</b>&nbsp;where it\'s status now is Allocated/Transferring</div><div style=\"\"><div class=\"gmail_default\" style=\"font-family: verdana, sans-serif; font-size: small;\"><br></div><div class=\"gmail_default\" style=\"font-family: verdana, sans-serif; font-size: small;\">The serial number(s) require your further action to acknowledge receive.</div></div></div>', '2020-10-21 08:36:52', '2021-05-04 03:16:28', 34, 11, 0),
(DEFAULT, 'Gold Return for BMMB Vault ', '##SERIALNO##||##OTHERPARAM_serialno##,##VAULTFROM##||##OTHERPARAM_vaultfrom##', 'Kilobar Return To Open Market', 'Dear Sir/ Madam,<div><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><br></font></div><div><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\">Please be informed that kilobar serial no&nbsp;<b>##SERIALNO##&nbsp;</b>from&nbsp;<b>##VAULTFROM##&nbsp;</b>was transferred out from <b>GTP</b>&nbsp;where it\'s status now is<b> Unallocated/Inactive</b>.</font></div><div><div class=\"gmail_default\" style=\"font-family: verdana, sans-serif; font-size: small;\"><br></div><div class=\"gmail_default\" style=\"font-family: verdana, sans-serif; font-size: small;\">The serial number(s) require your further action to book to SAP soonest.</div></div>', '2021-05-03 09:28:27', '2021-05-04 03:15:38', 11, 11, 0);
