
INSERT INTO `eventtrigger` (`etr_id`, `etr_grouptypeid`, `etr_moduleid`, `etr_actionid`, `etr_matcherclass`, `etr_processorclass`, `etr_messageid`, `etr_observableclass`, `etr_oldstatus`, `etr_newstatus`, `etr_objectclass`, `etr_storetolog`, `etr_groupidfieldname`, `etr_evalcode`, `etr_createdon`, `etr_modifiedon`, `etr_status`, `etr_createdby`, `etr_modifiedby`) VALUES
(DEFAULT, 0, 3, 11, '\\Snap\\object\\DefaultEventTriggerMatcher', '\\Snap\\object\\EmailEventProcessor', 11, '\\Snap\\manager\\BankVaultManager', 1, 5, '\\Snap\\object\\VaultItem', '1', 'partnerid', '', '2021-05-11 05:51:34', '2021-05-11 05:51:34', 1, 11, 11),
(DEFAULT, 0, 3, 11, '\\Snap\\object\\DefaultEventTriggerMatcher', '\\Snap\\object\\EmailEventProcessor', 12, '\\Snap\\manager\\BankVaultManager', 5, 1, '\\Snap\\object\\VaultItem', '1', 'partnerid', '', '2021-05-11 05:52:30', '2021-05-11 05:52:30', 1, 11, 11);



INSERT INTO `eventmessage` (`evm_id`, `evm_code`, `evm_replace`, `evm_subject`, `evm_content`, `evm_createdon`, `evm_modifiedon`, `evm_createdby`, `evm_modifiedby`, `evm_status`) VALUES
(DEFAULT, 'EasiGold Kilo bar Activation Request', '##SERIALNO##||##OTHERPARAM_serialno##,##REQUESTEDBY##||##OTHERPARAM_requestedby##', 'EasiGold Kilo bar Activation Request', '<font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">â€‹Please be informed we need the following kilo bar serial number to be activated in order to transfer to BMMB vault.&nbsp;</span></font><div style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; font-size: 13px;\"><br></div><div style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; font-size: 13px;\">The following serial numbers are requested by ##REQUESTEDBY##</div><div style=\"font-size: 13px; font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; color: rgb(0, 0, 0);\">##SERIALNO##</div><div style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; font-size: 13px;\"><br></div><div style=\"\"><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">Your approval is sought.</span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\"><br></span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">Thank you</span></font></div></div><div style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; font-size: 13px;\"><br></div>', '2021-05-11 05:48:49', '2021-05-11 06:25:07', 11, 11, 0),
(DEFAULT, 'EasiGold Kilo bar Activation Approved', '##SERIALNO##||##OTHERPARAM_serialno##,##APPROVEDBY##||##OTHERPARAM_approvedby##', 'EasiGold Kilo bar Activation Approved', '<span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, helvetica, arial, verdana, sans-serif; font-size: 13px;\">â€‹</span><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">Your request for the following kilo bar serial number to be activated in used for BMMB has been approved.</span></font><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\"><br></span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">The following serial numbers has been approved by ##APPROVEDBY##</span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">##SERIALNO##</span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\"><br></span></font></div><div style=\"\"><font face=\"Open Sans, Helvetica Neue, helvetica, arial, verdana, sans-serif\"><span style=\"font-size: 13px;\">Thank you</span></font></div>', '2021-05-11 05:49:24', '2021-05-11 08:22:29', 11, 11, 0);
